vich_uploader:
    db_driver: orm

    mappings:
        song_record:
            uri_prefix: /songs/records
            upload_destination: '%app.records_path%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

