vich_uploader:
    db_driver: orm

    mappings:
        song_record:
            uri_prefix: /uploads/records
            upload_destination: '%app.absolute_records_path%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

